#!/usr/bin/env bash
# install nginx with hello world at /

sudo apt-get update -qq && \
sudo apt-get install nginx -y

#sudo systemctl start nginx
sudo service nginx start
# sudo nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# ownership stuff
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# === hello world content ===
sudo echo "Hello World!" > /var/www/html/inex.nginx-debian.html

sudo nginx -s reload

